site_name: StarWaper
site_authro: StarWaper
site_description: StarWaper's Personal Website

nav:
  - 学习笔记:
    - STUDY/KalmanFilter.md
  - 网站:
    - TEST/test.md

theme:
  name: material
  language: zh

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
